proc casutil;
    droptable incaslib="CASUSER" casdata="SCORE_THIS_ON_THE_FLY" quiet;
run;QUIT;

DATA CASUSER.SCORE_THIS_ON_THE_FLY(PROMOTE=YES);
SET CASUSER.PUREPREM_DATA;

KEEP AGE BLUEBOOK CAR_AGE CARUSE CAR_TYPE GENDER MARITAL_STATUS OCCUPATION uniqueRecordID ;

RUN;








