
/* MACRO BELOW IS OUT TARGET VARIABLES */
%LET FLOW_TRGT_VAR=PUREPREMIUM; 

/* MACRO BELOW WILL DEFINE OUT SOURCE TABLE */
%LET FLOW_SRC_TABLE=CASUSER.PUREPREM_W_DATAPREP;

%LET NBR_VARS_MAX = 50;

%LET MODEL_DISTRIBUTION=Tweedie;
